### ISSUE TITLE
Image resizing service

### ISSUE THREAD

**Issue by jhauswald** [clinc/clarityeco#12]
- Description: this service receives images and resizes them according to the user's requested image size. Develop efficient backend resizing backend.
- Input: images, desired height and width
- Output: resized images
- Potential dependencies: opencv, thrift

**Comment by Lilisys** [comment]
I'd like to take this on. Currently looking into [Developer's Image Library](https://github.com/DentonW/DevIL) for this.

**Comment by jhauswald** [comment]
OpenCV also has resizing, it'd be good if we used 1 image processing framework across the services. Check other open source frameworks though, I heard openCV wasn't the best open source available anymore.

**Comment by Lilisys** [comment]
Ahh that's right I had forgotten about OpenCV. Where'd you hear that from? My google searches are bringing up OpenCV as the top option for image processing related tasks.

**Comment by jhauswald** [comment]
The library I was thinking about is OpenVX from the Khronos group: https://www.khronos.org/openvx/

It looks a little more complex and probably not as widely documented/on stackoverflow but I've heard its faster and we are in the business of optimizing so that's why I thought about it. Could you actually look into it and see what the differences are? It could be useful to investigate what exactly it provides not just for image resizing but in general.

**Comment by Lilisys** [comment]
So I read a bit about OpenVX from their website and on wikipedia. A lot of it was a bit too technical for me to fully understand, but I think the main features are that :
- It's targeted at **low power**, real time applications (like mobile and embedded platforms)
- It optimizes by using **graph-based executions** of image operations (which help eliminate memory transfers)

[These slides](https://www.khronos.org/assets/uploads/developers/library/overview/openvx-overview.pdf) contain basically the same information as the front page but with additional diagrams. Slide 9 compares OpenCV to OpenVX.

The following paragraph was taken from [videantis](http://www.videantis.com/the-khronos-family-has-a-new-baby-openvx.html)

>How does OpenVX relate to OpenCV, the other computer vision library that’s used a lot in the industry? OpenCV includes 1000s of imaging and vision functions, has seen over 6 million downloads, and is used a lot, both in academia as well as in industry. At the same time, OpenCV is hard to accelerate efficiently without proprietary extensions, mainly due to its frame-based means of operation, where each function typically reads and writes to external memory. OpenCV is also not controlled by a standardization body, which means many different versions of the library are in use, and platform support typically isn’t out-of-the-box, but needs to be handled by the application programmer. OpenVX has a different focus. It’s much smaller than OpenCV, with fewer functions, but is standardized, with conformance tests and a certification process. It also lends itself more easily to efficient implementations due to its graph-based architecture.

It seems like with our existing architecture (using OpenCV), GPU is the best optimization we have. OpenVX allows for optimizations on systems without GPU's, but is flexible enough that it does also support ISPs, Dedicated hardware, DSPs and DSP arrays, GPUs, and Multi-core CPUs.

**Comment by Lilisys** [comment]
For the purpose of image resizing, I feel like OpenVX isn't necessary, but for future computer vision research (e.g. mobile image processing - having an instance of sirius/cc running on a device rather than connecting to a server and being able to run image services) it's probably worth looking into.

**Comment by Lilisys** [comment]
So yesterday we chatted a bit about how we want the resizing to work, in terms of cropping vs scaling. I feel like we can't just arbitrarily crop or scale. For example,

Let's say we want to run imc with this:
![chickadee1](https://cloud.githubusercontent.com/assets/6434961/8831967/e6cf0e38-3073-11e5-9f1f-cbec220bffff.jpg)

We can scale it down to 227x227, resulting in this:
![chickadee2](https://cloud.githubusercontent.com/assets/6434961/8831966/e6cf085c-3073-11e5-807c-9f623f4bdb99.jpg)

And if we cropped it to 227x227, we get this:
![chickadee3](https://cloud.githubusercontent.com/assets/6434961/8831968/e6d015ee-3073-11e5-87a6-2bfd672b7457.jpg)

Would imc be able to run correctly on either of those? Or would we need a resized image like this for it to run properly?
![chickadee4](https://cloud.githubusercontent.com/assets/6434961/8831969/e6d256f6-3073-11e5-8ba1-6d1c7a646eca.jpg)

I used photoshop to resize each of these, and for the last one I first cropped it to the largest possible square then shrank it down. Should I use that algorithm instead of purely cropping or purely scaling? It would probably take longer to run since it involves both steps. 

Also, what happens if the subject/thing we want to analyze (like a face) isn't right in the middle? Is the resizing service going to detect where the subject is and resize around that? Or is it the client's job to do some preprocessing (like sending a square image or cropping their image so that the face is in the middle)?

**Comment by Lilisys** [comment]
I wrote a service that uses pure scaling, which works with the command center and a test client. Currently integrating it into tonic-image.

**Comment by Lilisys** [comment]
I wrote some functions that convert an image into a stringstream and vice versa that are used in both tonic-image as well as this resizing service. What's the best place to put this? Should I just create a common source folder for all the services and stick it there? The other option is to put it in the src folder of one of the services and have the other link to it, but that makes the service feel less modular.
