### ISSUE TITLE
ASR Enhancements

### ISSUE THREAD

**Issue by jhauswald** [clinc/clarityeco#26]
- update readme
- standardize command line arguments
- move apt-get packages into readme or separate script, don't want to have everything owned by root when running `./prepare.sh`

**Comment by cdmeister** [comment]
Is there any documentation/email on how you want to standardize command line args?

**Comment by jhauswald** [comment]
@Lilisys is working on that. Could you open an issue describing it and starting the conversation?

**Comment by cdmeister** [comment]
ok!

**Comment by cdmeister** [comment]
In the Readme, do you want me to list the dependencies as well?

**Comment by jhauswald** [comment]
yea

**Comment by cdmeister** [comment]
Original plan for this issue was make some adjustments for asr kaldi, but new plan is to use this issue to convert the kaldi asr to work with the new command center #15.

Changes to be made:
1. Convert to ipa service
2. Edit Documentation to conform to clarityinc standards #23 
3. fix prepare script 
4. use boost program options to standardize args #27

**Comment by cdmeister** [comment]
I am starting to work on this. Also I will make a travis ci build for this as well.

**Comment by cdmeister** [comment]
Almost forgot, in #33, ben created a regex parsing which is in the command center, I am gonna move this to asr and its been test already with a demo and works well.

**Comment by cdmeister** [comment]
It turns out that Ben's regex parsing also modifies the inside portion of the string as well. I am going to fix this.

**Comment by cdmeister** [comment]
The modified Regex parsing engine is inserted into ASR and is passing all of the testcases.
